require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/product');

const generateSlug = (name) =>
    name
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/đ/g, 'd')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');

// Ảnh Cloudinary — cập nhật tại file này rồi chạy: node src/seed.js
const IMG = {
    ring: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989485/nhan-dinh-hon-r268-white-gold-gallery-01-1.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989488/nhan-dinh-hon-r268-white-gold-gallery-01.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989489/nhan-dinh-hon-r268-white-gold-gallery-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989490/nhan-dinh-hon-r481-gold-gallery-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989491/nhan-dinh-hon-r481-gold-thumb.jpg',
    ],
    bracelet: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989492/vong-swarovski-chinh-hang-blue-gema-bracelet-01-jp.webp',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989493/vong-swarovski-chinh-hang-blue-gema-bracelet-01-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989494/vong-swarovski-chinh-hang-blue-gema-bracelet-02-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989541/vong-swarovski-chinh-hang-blue-gema-bracelet-03-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989542/vong-swarovski-chinh-hang-blue-gema-bracelet-04-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989543/vong-swarovski-chinh-hang-blue-gema-bracelet-07-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989544/vong-tay-swarovski-thien-nga-chinh-hang-dazzling-s.jpg',
    ],
    necklace: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030602/day-chuyen-daniel-wellington-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030603/day-chuyen-daniel-wellington-lumine-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030604/day-chuyen-daniel-wellington-pave-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030605/day-chuyen-daniel-wellington-pave-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030607/day-chuyen-swarovski-chinh-hang-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030608/day-chuyen-swarovski-chinh-hang-22.jpg',
    ],
    necklaceDw: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030602/day-chuyen-daniel-wellington-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030603/day-chuyen-daniel-wellington-lumine-02.jpg',
    ],
    necklaceDwPave: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030604/day-chuyen-daniel-wellington-pave-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030605/day-chuyen-daniel-wellington-pave-03.jpg',
    ],
    necklaceSwarovski: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030607/day-chuyen-swarovski-chinh-hang-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030608/day-chuyen-swarovski-chinh-hang-22.jpg',
    ],
    earring: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995755/bong-tai-swarovski-chinh-hang-angelic-stud-earring.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995758/hoa-tai-swarovski-chinh-hang-stone-hoop-earrings-0.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030808/hoa-tai-swarovski-chinh-hang-stone-hoop02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030809/hoa-tai-swarovski-chinh-hang-stone-hoop-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030806/bong-tai-swarovski-chinh-hang-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030807/bong-tai-swarovski-chinh-hang-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030810/khuyen-tai-swarrovski-heart-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030811/khuyen-tai-swarrovski-heart-chroma-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995760/khuyen-tai-swarrovski-heart-chroma-drop-earrings-0.jpg',
    ],
    earringStud: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995755/bong-tai-swarovski-chinh-hang-angelic-stud-earring.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030806/bong-tai-swarovski-chinh-hang-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030807/bong-tai-swarovski-chinh-hang-03.jpg',
    ],
    earringHoop: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995758/hoa-tai-swarovski-chinh-hang-stone-hoop-earrings-0.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030808/hoa-tai-swarovski-chinh-hang-stone-hoop02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030809/hoa-tai-swarovski-chinh-hang-stone-hoop-03.jpg',
    ],
    earringHeart: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030810/khuyen-tai-swarrovski-heart-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030811/khuyen-tai-swarrovski-heart-chroma-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995760/khuyen-tai-swarrovski-heart-chroma-drop-earrings-0.jpg',
    ],
    pendant: [
        'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600',
        'https://images.unsplash.com/photo-1603561596112-0a132b757442?w=600',
    ],
    wedding: [
        'https://images.unsplash.com/photo-1515562141203-7a88fb7ce338?w=600',
        'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600',
        'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600',
    ],
};

const rawProducts = [
    // ─── NHẪN ───
    {
        name: 'Nhẫn Đính Hôn R268 Vàng Trắng',
        category: 'Nhan',
        price: 12500000,
        originalPrice: 15800000,
        discount: 21,
        stock: 5,
        sold: 47,
        material: 'Vang 18K',
        weight: 3.5,
        gemstone: 'Kim cương 0.5ct',
        description: 'Nhẫn vàng 18K đính kim cương hồng tâm sang trọng, thiết kế tinh tế, phù hợp cho ngày trọng đại. Kim cương được cắt gọt chuẩn GIA, ánh sáng lấp lánh.',
        shortDescription: 'Nhẫn kim cương sang trọng, thiết kế độc đáo',
        images: IMG.ring,
        isNew: true,
        isHot: true,
        rating: 4.8,
        totalReviews: 23,
    },
    {
        name: 'Nhẫn Cưới Vàng Trắng',
        category: 'Nhan',
        price: 8900000,
        originalPrice: 11200000,
        discount: 20,
        stock: 8,
        sold: 62,
        material: 'Vang 14K',
        weight: 2.8,
        description: 'Nhẫn cưới vàng trắng 14K thiết kế đơn giản nhưng sang trọng, biểu tượng cho tình yêu vĩnh cửu.',
        shortDescription: 'Nhẫn cưới vàng trắng sang trọng',
        images: [IMG.ring[1], IMG.ring[2]],
        isNew: true,
        rating: 4.9,
        totalReviews: 45,
    },
    {
        name: 'Nhẫn Solitaire Kim Cương',
        category: 'Nhan',
        price: 22500000,
        stock: 3,
        sold: 18,
        material: 'Platinum',
        weight: 4.2,
        gemstone: 'Kim cương 1ct',
        description: 'Nhẫn solitaire bạch kim đính kim cương 1 carat, kiểu dáng cổ điển vượt thời gian.',
        shortDescription: 'Nhẫn solitaire kim cương 1ct',
        images: IMG.ring,
        isHot: true,
        rating: 5.0,
        totalReviews: 12,
    },
    {
        name: 'Nhẫn Vàng Hoa Văn Cổ Điển',
        category: 'Nhan',
        price: 5600000,
        originalPrice: 7200000,
        discount: 22,
        stock: 12,
        sold: 89,
        material: 'Vang 18K',
        weight: 3.1,
        description: 'Nhẫn vàng 18K chạm khắc hoa văn cổ điển, phù hợp đeo hàng ngày hoặc dự tiệc.',
        shortDescription: 'Nhẫn vàng hoa văn cổ điển',
        images: [IMG.ring[0], IMG.ring[1]],
        isSale: true,
        rating: 4.6,
        totalReviews: 31,
    },
    {
        name: 'Nhẫn Đôi Ruby Đỏ',
        category: 'Nhan',
        price: 9800000,
        stock: 6,
        sold: 34,
        material: 'Vang 14K',
        weight: 2.5,
        gemstone: 'Ruby Myanmar',
        description: 'Nhẫn vàng 14K đính đôi ruby đỏ Myanmar tự nhiên, mang lại may mắn và tài lộc.',
        shortDescription: 'Nhẫn ruby đỏ may mắn',
        images: IMG.ring,
        isNew: true,
        rating: 4.7,
        totalReviews: 19,
    },
    {
        name: 'Nhẫn Bạc Đá Sapphire Xanh',
        category: 'Nhan',
        price: 2200000,
        originalPrice: 2800000,
        discount: 21,
        stock: 20,
        sold: 156,
        material: 'Bac',
        weight: 2.0,
        gemstone: 'Sapphire xanh',
        description: 'Nhẫn bạc 925 đính đá sapphire xanh, thiết kế trẻ trung, giá cả phải chăng.',
        shortDescription: 'Nhẫn bạc sapphire xanh trẻ trung',
        images: [IMG.ring[2], IMG.ring[0]],
        isHot: true,
        isSale: true,
        rating: 4.5,
        totalReviews: 67,
    },

    // ─── VÒNG TAY ───
    {
        name: 'Vòng Tay Swarovski Blue Gema Chính Hãng',
        category: 'Vong tay',
        price: 3500000,
        originalPrice: 4500000,
        discount: 22,
        stock: 12,
        sold: 78,
        material: 'Bac',
        weight: 8.5,
        gemstone: 'Ngọc trai tự nhiên',
        description: 'Vòng tay bạc kết hợp ngọc trai tự nhiên, mang đến vẻ đẹp thanh lịch và quý phái.',
        shortDescription: 'Vòng tay ngọc trai thanh lịch',
        images: IMG.bracelet,
        isHot: true,
        rating: 4.7,
        totalReviews: 34,
    },
    {
        name: 'Vòng Tay Vàng 18K Hoa Văn',
        category: 'Vong tay',
        price: 15800000,
        stock: 6,
        sold: 22,
        material: 'Vang 18K',
        weight: 6.2,
        description: 'Vòng tay vàng 18K chạm khắc hoa văn tinh xảo, sản phẩm thủ công cao cấp.',
        shortDescription: 'Vòng tay vàng hoa văn tinh xảo',
        images: [IMG.bracelet[1], IMG.bracelet[2]],
        isNew: true,
        rating: 5.0,
        totalReviews: 12,
    },
    {
        name: 'Vòng Tay Charm Vàng 14K',
        category: 'Vong tay',
        price: 7200000,
        originalPrice: 9000000,
        discount: 20,
        stock: 9,
        sold: 45,
        material: 'Vang 14K',
        weight: 5.8,
        description: 'Vòng tay charm vàng 14K với các mặt dây mini đá quý, phong cách cá nhân hóa.',
        shortDescription: 'Vòng tay charm vàng 14K',
        images: IMG.bracelet,
        isSale: true,
        rating: 4.8,
        totalReviews: 28,
    },
    {
        name: 'Vòng Tay Bạc Khắc Chữ Phúc',
        category: 'Vong tay',
        price: 1800000,
        stock: 25,
        sold: 203,
        material: 'Bac',
        weight: 12.0,
        description: 'Vòng tay bạc khắc chữ Phúc, mang ý nghĩa may mắn, tài lộc trong phong thủy.',
        shortDescription: 'Vòng tay bạc phong thủy may mắn',
        images: [IMG.bracelet[0], IMG.bracelet[1]],
        isHot: true,
        rating: 4.4,
        totalReviews: 89,
    },
    {
        name: 'Vòng Tay Kim Cương Tennis',
        category: 'Vong tay',
        price: 35000000,
        stock: 2,
        sold: 8,
        material: 'Platinum',
        weight: 8.0,
        gemstone: 'Kim cương 2ct tổng',
        description: 'Vòng tay tennis bạch kim đính kim cương liên tục, biểu tượng của sự sang trọng tuyệt đối.',
        shortDescription: 'Vòng tay tennis kim cương cao cấp',
        images: IMG.bracelet,
        isNew: true,
        isHot: true,
        rating: 5.0,
        totalReviews: 5,
    },
    {
        name: 'Vòng Tay Đá Mã Não Đỏ',
        category: 'Vong tay',
        price: 2800000,
        originalPrice: 3500000,
        discount: 20,
        stock: 15,
        sold: 67,
        material: 'Vang 10K',
        weight: 7.5,
        gemstone: 'Mã não đỏ',
        description: 'Vòng tay vàng 10K kết hợp hạt mã não đỏ tự nhiên, bảo vệ sức khỏe theo phong thủy.',
        shortDescription: 'Vòng tay mã não phong thủy',
        images: [IMG.bracelet[2], IMG.bracelet[0]],
        isSale: true,
        rating: 4.6,
        totalReviews: 41,
    },

    // ─── DÂY CHUYỀN ───
    {
        name: 'Dây Chuyền Daniel Wellington Classic',
        category: 'Day chuyen',
        price: 4200000,
        originalPrice: 5600000,
        discount: 25,
        stock: 10,
        sold: 56,
        material: 'Bac',
        weight: 2.5,
        gemstone: 'Pha lê',
        description: 'Dây chuyền Daniel Wellington thiết kế tối giản, sang trọng, phù hợp phong cách hiện đại.',
        shortDescription: 'Dây chuyền Daniel Wellington classic',
        images: IMG.necklaceDw,
        isHot: true,
        isSale: true,
        rating: 4.6,
        totalReviews: 28,
    },
    {
        name: 'Dây Chuyền Daniel Wellington Lumine',
        category: 'Day chuyen',
        price: 6800000,
        stock: 7,
        sold: 38,
        material: 'Bac',
        weight: 3.2,
        gemstone: 'Pha lê',
        description: 'Dây chuyền Daniel Wellington Lumine lấp lánh, thiết kế thanh lịch cho phụ nữ hiện đại.',
        shortDescription: 'Dây chuyền DW Lumine chính hãng',
        images: IMG.necklaceDw,
        isNew: true,
        rating: 4.9,
        totalReviews: 19,
    },
    {
        name: 'Dây Chuyền Daniel Wellington Pavé',
        category: 'Day chuyen',
        price: 18500000,
        stock: 4,
        sold: 15,
        material: 'Vang 14K',
        weight: 8.5,
        gemstone: 'Pha lê',
        description: 'Dây chuyền Daniel Wellington Pavé đính đá lấp lánh, phong cách cao cấp.',
        shortDescription: 'Dây chuyền DW Pavé cao cấp',
        images: IMG.necklaceDwPave,
        isHot: true,
        rating: 4.8,
        totalReviews: 11,
    },
    {
        name: 'Dây Chuyền Swarovski Chính Hãng',
        category: 'Day chuyen',
        price: 5200000,
        originalPrice: 6500000,
        discount: 20,
        stock: 11,
        sold: 72,
        material: 'Bac',
        weight: 4.0,
        gemstone: 'Pha lê Swarovski',
        description: 'Dây chuyền Swarovski chính hãng, đá pha lê sáng rực, thiết kế tinh xảo.',
        shortDescription: 'Dây chuyền Swarovski chính hãng',
        images: IMG.necklaceSwarovski,
        isSale: true,
        rating: 4.7,
        totalReviews: 36,
    },
    {
        name: 'Dây Chuyền Bạc Mặt Phật',
        category: 'Day chuyen',
        price: 1500000,
        stock: 30,
        sold: 189,
        material: 'Bac',
        weight: 5.5,
        description: 'Dây chuyền bạc mặt Phật Di Lặc, mang bình an và may mắn cho người đeo.',
        shortDescription: 'Dây chuyền bạc phong thủy bình an',
        images: IMG.necklaceDwPave,
        isHot: true,
        rating: 4.3,
        totalReviews: 95,
    },
    {
        name: 'Dây Chuyền Kim Cương Solitaire',
        category: 'Day chuyen',
        price: 28000000,
        stock: 2,
        sold: 6,
        material: 'Platinum',
        weight: 3.8,
        gemstone: 'Kim cương 0.8ct',
        description: 'Dây chuyền bạch kim mặt kim cương solitaire 0.8ct, kiểu dáng thanh lịch cho phụ nữ hiện đại.',
        shortDescription: 'Dây chuyền kim cương solitaire',
        images: IMG.necklaceSwarovski,
        isNew: true,
        rating: 5.0,
        totalReviews: 4,
    },

    // ─── BÔNG TAI ───
    {
        name: 'Bông Tai Swarovski Angelic Stud',
        category: 'Bong tai',
        price: 18900000,
        stock: 4,
        sold: 21,
        material: 'Bac',
        weight: 1.8,
        gemstone: 'Pha lê Swarovski',
        description: 'Bông tai Swarovski Angelic Stud chính hãng, thiết kế sang trọng, đẳng cấp.',
        shortDescription: 'Bông tai Swarovski Angelic',
        images: IMG.earringStud,
        isHot: true,
        rating: 5.0,
        totalReviews: 8,
    },
    {
        name: 'Hoa Tai Swarovski Stone Hoop',
        category: 'Bong tai',
        price: 2800000,
        originalPrice: 3800000,
        discount: 26,
        stock: 15,
        sold: 134,
        material: 'Bac',
        weight: 2.1,
        gemstone: 'Pha lê Swarovski',
        description: 'Hoa tai Swarovski Stone Hoop chính hãng, nhẹ nhàng, nữ tính.',
        shortDescription: 'Hoa tai Swarovski hoop',
        images: IMG.earringHoop,
        isSale: true,
        rating: 4.5,
        totalReviews: 42,
    },
    {
        name: 'Khuyên Tai Swarovski Heart Chroma',
        category: 'Bong tai',
        price: 4500000,
        stock: 10,
        sold: 58,
        material: 'Bac',
        weight: 1.5,
        gemstone: 'Pha lê Swarovski',
        description: 'Khuyên tai Swarovski Heart Chroma chính hãng, phong cách thanh lịch hiện đại.',
        shortDescription: 'Khuyên tai Swarovski Heart',
        images: IMG.earringHeart,
        isNew: true,
        rating: 4.8,
        totalReviews: 25,
    },
    {
        name: 'Bông Tai Swarovski Chính Hãng Premium',
        category: 'Bong tai',
        price: 12500000,
        stock: 5,
        sold: 19,
        material: 'Bac',
        weight: 3.2,
        gemstone: 'Pha lê Swarovski',
        description: 'Bông tai Swarovski Premium đính pha lê, ánh sáng lấp lánh đẳng cấp.',
        shortDescription: 'Bông tai Swarovski Premium',
        images: IMG.earringStud,
        isHot: true,
        rating: 4.9,
        totalReviews: 14,
    },
    {
        name: 'Bông Tai Khuyên Tròn Vàng',
        category: 'Bong tai',
        price: 3200000,
        originalPrice: 4000000,
        discount: 20,
        stock: 18,
        sold: 97,
        material: 'Vang 10K',
        weight: 1.2,
        description: 'Bông tai khuyên tròn vàng 10K, thiết kế tối giản, dễ phối đồ hàng ngày.',
        shortDescription: 'Bông tai khuyên vàng tối giản',
        images: IMG.earringHoop,
        isSale: true,
        rating: 4.4,
        totalReviews: 53,
    },
    {
        name: 'Bông Tai Đá Citrine Vàng',
        category: 'Bong tai',
        price: 1900000,
        stock: 22,
        sold: 112,
        material: 'Bac',
        weight: 1.8,
        gemstone: 'Citrine',
        description: 'Bông tai bạc đính đá citrine vàng, thu hút tài lộc và năng lượng tích cực.',
        shortDescription: 'Bông tai citrine thu hút tài lộc',
        images: IMG.earringHeart,
        rating: 4.3,
        totalReviews: 38,
    },

    // ─── MẶT DÂY ───
    {
        name: 'Mặt Dây Tứ Linh',
        category: 'Mat day',
        price: 5500000,
        stock: 9,
        sold: 43,
        material: 'Vang 18K',
        weight: 4.5,
        gemstone: 'Ngọc bích',
        description: 'Mặt dây vàng 18K khắc hình tứ linh, phong thủy may mắn.',
        shortDescription: 'Mặt dây phong thủy may mắn',
        images: IMG.pendant,
        isNew: true,
        rating: 4.8,
        totalReviews: 15,
    },
    {
        name: 'Mặt Dây Phật Di Lặc',
        category: 'Mat day',
        price: 3800000,
        originalPrice: 4800000,
        discount: 21,
        stock: 14,
        sold: 76,
        material: 'Vang 14K',
        weight: 5.0,
        description: 'Mặt dây vàng 14K tạc Phật Di Lặc, mang lại bình an và hạnh phúc.',
        shortDescription: 'Mặt dây Phật Di Lặc bình an',
        images: [IMG.pendant[0], IMG.pendant[1]],
        isHot: true,
        isSale: true,
        rating: 4.6,
        totalReviews: 32,
    },
    {
        name: 'Mặt Dây Kim Cương Tròn',
        category: 'Mat day',
        price: 15000000,
        stock: 3,
        sold: 11,
        material: 'Platinum',
        weight: 2.8,
        gemstone: 'Kim cương 0.5ct',
        description: 'Mặt dây bạch kim đính kim cương tròn 0.5ct, có thể kết hợp với mọi loại dây chuyền.',
        shortDescription: 'Mặt dây kim cương đa năng',
        images: IMG.pendant,
        isNew: true,
        rating: 5.0,
        totalReviews: 7,
    },
    {
        name: 'Mặt Dây 12 Con Giáp',
        category: 'Mat day',
        price: 4200000,
        stock: 16,
        sold: 88,
        material: 'Vang 10K',
        weight: 3.5,
        description: 'Mặt dây vàng 10K khắc 12 con giáp, chọn theo năm sinh của bạn.',
        shortDescription: 'Mặt dây 12 con giáp theo tuổi',
        images: [IMG.pendant[1], IMG.pendant[0]],
        isHot: true,
        rating: 4.5,
        totalReviews: 44,
    },
    {
        name: 'Mặt Dây Ngọc Bích Myanmar',
        category: 'Mat day',
        price: 8900000,
        stock: 5,
        sold: 27,
        material: 'Vang 18K',
        weight: 6.0,
        gemstone: 'Ngọc bích Myanmar',
        description: 'Mặt dây vàng 18K đính ngọc bích Myanmar A-grade, màu xanh đậm quý phái.',
        shortDescription: 'Mặt dây ngọc bích Myanmar cao cấp',
        images: IMG.pendant,
        rating: 4.9,
        totalReviews: 16,
    },
    {
        name: 'Mặt Dây Bạc Thần Tài',
        category: 'Mat day',
        price: 1200000,
        stock: 0,
        sold: 245,
        material: 'Bac',
        weight: 4.0,
        description: 'Mặt dây bạc Thần Tài, biểu tượng thu hút tài lộc trong văn hóa Việt Nam.',
        shortDescription: 'Mặt dây bạc Thần Tài tài lộc',
        images: [IMG.pendant[0], IMG.pendant[1]],
        isHot: true,
        rating: 4.2,
        totalReviews: 102,
    },

    // ─── TRANG SỨC CƯỚI ───
    {
        name: 'Bộ Trang Sức Cưới Kim Cương',
        category: 'Trang suc cuoi',
        price: 45000000,
        stock: 2,
        sold: 5,
        material: 'Platinum',
        weight: 15.0,
        gemstone: 'Kim cương 2ct tổng',
        description: 'Bộ trang sức cưới gồm nhẫn, dây chuyền và bông tai kim cương, thiết kế đồng bộ sang trọng.',
        shortDescription: 'Bộ trang sức cưới kim cương cao cấp',
        images: IMG.wedding,
        isNew: true,
        isHot: true,
        rating: 5.0,
        totalReviews: 3,
    },
    {
        name: 'Nhẫn Cưới Đôi Vàng 18K',
        category: 'Trang suc cuoi',
        price: 12000000,
        originalPrice: 15000000,
        discount: 20,
        stock: 6,
        sold: 34,
        material: 'Vang 18K',
        weight: 5.6,
        description: 'Cặp nhẫn cưới vàng 18K thiết kế đôi, khắc tên theo yêu cầu, biểu tượng tình yêu vĩnh cửu.',
        shortDescription: 'Cặp nhẫn cưới vàng 18K đôi',
        images: [IMG.wedding[0], IMG.wedding[1]],
        isSale: true,
        rating: 4.9,
        totalReviews: 22,
    },
    {
        name: 'Dây Chuyền Cưới Ngọc Trai',
        category: 'Trang suc cuoi',
        price: 8500000,
        stock: 8,
        sold: 28,
        material: 'Vang 14K',
        weight: 6.5,
        gemstone: 'Ngọc trai',
        description: 'Dây chuyền cưới vàng 14K kết hợp ngọc trai, thanh lịch cho cô dâu ngày trọng đại.',
        shortDescription: 'Dây chuyền cưới ngọc trai thanh lịch',
        images: IMG.wedding,
        isNew: true,
        rating: 4.8,
        totalReviews: 17,
    },
    {
        name: 'Bông Tai Cô Dâu Kim Cương',
        category: 'Trang suc cuoi',
        price: 22000000,
        stock: 3,
        sold: 9,
        material: 'Platinum',
        weight: 2.5,
        gemstone: 'Kim cương 0.5ct',
        description: 'Bông tai cô dâu bạch kim đính kim cương, thiết kế chandelier lấp lánh.',
        shortDescription: 'Bông tai cô dâu kim cương lấp lánh',
        images: [IMG.wedding[1], IMG.wedding[2]],
        isHot: true,
        rating: 5.0,
        totalReviews: 6,
    },
    {
        name: 'Vòng Tay Cưới Vàng Trắng',
        category: 'Trang suc cuoi',
        price: 6800000,
        originalPrice: 8500000,
        discount: 20,
        stock: 10,
        sold: 41,
        material: 'Vang 14K',
        weight: 4.8,
        description: 'Vòng tay cưới vàng trắng 14K, thiết kế mảnh mai phù hợp đeo cùng váy cưới.',
        shortDescription: 'Vòng tay cưới vàng trắng mảnh mai',
        images: [IMG.wedding[0], IMG.wedding[2]],
        isSale: true,
        rating: 4.7,
        totalReviews: 19,
    },
    {
        name: 'Bộ Nhẫn Cưới Bạc Đôi',
        category: 'Trang suc cuoi',
        price: 3500000,
        stock: 20,
        sold: 167,
        material: 'Bac',
        weight: 4.0,
        description: 'Bộ nhẫn cưới bạc 925 đôi, giá cả phải chăng, thiết kế đơn giản thanh lịch.',
        shortDescription: 'Bộ nhẫn cưới bạc giá tốt',
        images: IMG.wedding,
        isHot: true,
        rating: 4.4,
        totalReviews: 78,
    },
];

const products = rawProducts.map((p) => ({
    ...p,
    slug: generateSlug(p.name),
}));

const seedDatabase = async () => {
    try {
        await mongoose.connect(process.env.MONGO_DB_URL);
        await Product.deleteMany({});
        await Product.insertMany(products);
        const counts = await Product.aggregate([
            { $group: { _id: '$category', count: { $sum: 1 } } },
        ]);
        console.log('Seed data thành công! Tổng:', products.length, 'sản phẩm');
        counts.forEach((c) => console.log(`  - ${c._id}: ${c.count} sản phẩm`));
        process.exit(0);
    } catch (error) {
        console.error('Lỗi seed:', error);
        process.exit(1);
    }
};

seedDatabase();
