require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/product');

const generateSlug = (name) =>
    name
        .toLowerCase()
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/đ/g, 'd')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');

// Ảnh Cloudinary — cập nhật tại file này rồi chạy: node src/seed.js
const IMG = {
    ring: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989485/nhan-dinh-hon-r268-white-gold-gallery-01-1.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989488/nhan-dinh-hon-r268-white-gold-gallery-01.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989489/nhan-dinh-hon-r268-white-gold-gallery-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989490/nhan-dinh-hon-r481-gold-gallery-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989491/nhan-dinh-hon-r481-gold-thumb.jpg',
    ],
    bracelet: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989492/vong-swarovski-chinh-hang-blue-gema-bracelet-01-jp.webp',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989493/vong-swarovski-chinh-hang-blue-gema-bracelet-01-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989494/vong-swarovski-chinh-hang-blue-gema-bracelet-02-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989541/vong-swarovski-chinh-hang-blue-gema-bracelet-03-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989542/vong-swarovski-chinh-hang-blue-gema-bracelet-04-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989543/vong-swarovski-chinh-hang-blue-gema-bracelet-07-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778989544/vong-tay-swarovski-thien-nga-chinh-hang-dazzling-s.jpg',
    ],
    braceletAngelic: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089666/vong-tay-10.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089667/vong-tay-11.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089668/vong-tay-12.jpg',
    ],
    braceletIdyllia: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089669/vong-tay-20.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089670/vong-tay-21.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089671/vong-tay-22.jpg',
    ],
    braceletMesmera: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089672/vong-tay-30.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089673/vong-tay-31.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089674/vong-tay-32.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089675/vong-tay-33.jpg',
    ],
    braceletHyperbola: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089881/vong-tay-40.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089883/vong-tay-41.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089884/vong-tay-42.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089885/vong-tay-43.jpg',
    ],
    braceletConstella: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089886/vong-tay-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089887/vong-tay-51.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089888/vong-tay-52.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779089889/vong-tay-53.jpg',
    ],
    necklace: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030602/day-chuyen-daniel-wellington-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030603/day-chuyen-daniel-wellington-lumine-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030604/day-chuyen-daniel-wellington-pave-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030605/day-chuyen-daniel-wellington-pave-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030607/day-chuyen-swarovski-chinh-hang-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030608/day-chuyen-swarovski-chinh-hang-22.jpg',
    ],
    necklaceDw: [

        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030603/day-chuyen-daniel-wellington-lumine-02.jpg',
    ],
    
    necklaceSwarovski: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030607/day-chuyen-swarovski-chinh-hang-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030608/day-chuyen-swarovski-chinh-hang-22.jpg',
    ],
    necklaceIdyllia: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090546/vong-co-1.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090548/vong-co-2.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090549/vong-co-3.jpg',
    ],
    necklaceConstella: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090550/vong-co-10.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090551/vong-co-11.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090552/vong-co-12.jpg',
    ],
    necklaceMatrix: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090553/vong-co-20.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090554/vong-co-21.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090554/vong-co-22.jpg',
    ],
    necklaceHyperbola: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090682/vong-co-30.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090683/vong-co-31.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090684/vong-co-32.jpg',
    ],
    necklaceSwanMedium: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090685/vong-co-40.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090686/vong-co-41.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090687/vong-co-42.jpg',
    ],
    necklaceSwanRose: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090687/vong-co-50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090688/vong-co-51.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779090689/vong-co-52.jpg',
    ],
    earring: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995755/bong-tai-swarovski-chinh-hang-angelic-stud-earring.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995758/hoa-tai-swarovski-chinh-hang-stone-hoop-earrings-0.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030808/hoa-tai-swarovski-chinh-hang-stone-hoop02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030809/hoa-tai-swarovski-chinh-hang-stone-hoop-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030806/bong-tai-swarovski-chinh-hang-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030807/bong-tai-swarovski-chinh-hang-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030810/khuyen-tai-swarrovski-heart-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030811/khuyen-tai-swarrovski-heart-chroma-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995760/khuyen-tai-swarrovski-heart-chroma-drop-earrings-0.jpg',
    ],
    earringStud: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995755/bong-tai-swarovski-chinh-hang-angelic-stud-earring.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030806/bong-tai-swarovski-chinh-hang-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030807/bong-tai-swarovski-chinh-hang-03.jpg',
    ],
    earringHoop: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995758/hoa-tai-swarovski-chinh-hang-stone-hoop-earrings-0.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030808/hoa-tai-swarovski-chinh-hang-stone-hoop02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030809/hoa-tai-swarovski-chinh-hang-stone-hoop-03.jpg',
    ],
    earringHeart: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030810/khuyen-tai-swarrovski-heart-03.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779030811/khuyen-tai-swarrovski-heart-chroma-02.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1778995760/khuyen-tai-swarrovski-heart-chroma-drop-earrings-0.jpg',
    ],
    earringMatrix: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091880/bongtai1.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091881/bongtai2.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091882/bongtai3.jpg',
    ],
    earringMagic: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091883/bongtai10.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091884/bongtai11.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091885/bongtai12.jpg',
    ],
    earringBella: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091886/bongtai20.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091887/bongtai21.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091888/bongtai22.jpg',
    ],
    earringSwanDancing: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779091889/bongtai30.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779092014/bongtai31.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779092018/bongtai32.jpg',
    ],
    earringSolitaire: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779092019/bongtai40.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779092020/bongtai41.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779092021/bongtai42.jpg',
    ],
    earringUnaAngelic: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779092022/bongtai50.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779092023/bongtai51.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779092024/bongtai52.jpg',
    ],
    pendant: [
        'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600',
        'https://images.unsplash.com/photo-1603561596112-0a132b757442?w=600',
    ],
    wedding: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779067789/nhandoi.png',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779067793/nhandoi22.png',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779067968/vong-tay-cuoi-vang-trang-22.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779067971/vong-tay-cuoi-vang-trang.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779068148/bo-trang-suc-cuoi-kim-cuong.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779068153/bo-trang-suc-cuoi-kim-cuong333.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779068152/bo-trang-suc-cuoi-kim-cuong22.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779068597/bong-tai-co-dau-kim-cuong.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779068599/bong-tai-co-dau-kim-cuong222.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779068803/anc04-nhan-cuoi-vang-vang.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779068806/anc118-1-nhan-cuoi-vang-vang-1.jpg',
    ],
    nhansolitairekimcuong: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779069290/nhan-solitaire-kim-cuong.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779069293/nhan-solitaire-kim-cuong333.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779069292/nhan-solitaire-kim-cuong111.jpg'
    ],
    nhanvanghoavancodien: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779087758/nhan-vang-hoa-van-co-dien.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779087760/nhan-vang-hoa-van-co-dien22.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779087761/nhan-vang-hoa-van-co-dien33.jpg',

    ],
    nhancuoivangtrang: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779068806/anc118-1-nhan-cuoi-vang-vang-1.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779068803/anc04-nhan-cuoi-vang-vang.jpg',
    ],
    nhanbacdaxanh: [
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779088344/nhan-bac-da-xanh.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779088346/nhan-bac-da-xanh-nu.jpg',
    ],
    nhandoibac :[
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779088650/nhan-cuoi-vang-trang.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779088651/nhan-cuoi-vang-trang22.jpg',
        'https://res.cloudinary.com/derte9ykz/image/upload/v1779088652/nhan-cuoi-vang-trang33.jpg',
    ]

};

const rawProducts = [
    // ─── NHẪN ───
    {
        name: 'Nhẫn Đính Hôn R268 Vàng Trắng',
        category: 'Nhan',
        price: 12500000,
        originalPrice: 15800000,
        discount: 21,
        stock: 5,
        sold: 47,
        material: 'Vang 18K',
        weight: 3.5,
        gemstone: 'Kim cương 0.5ct',
        description: 'Nhẫn vàng 18K đính kim cương hồng tâm sang trọng, thiết kế tinh tế, phù hợp cho ngày trọng đại. Kim cương được cắt gọt chuẩn GIA, ánh sáng lấp lánh.',
        shortDescription: 'Nhẫn kim cương sang trọng, thiết kế độc đáo',
        images: IMG.ring,
        isNew: true,
        isHot: true,
        rating: 4.8,
        totalReviews: 23,
    },
    {
        name: 'Nhẫn Cưới Vàng Trắng',
        category: 'Nhan',
        price: 8900000,
        originalPrice: 11200000,
        discount: 20,
        stock: 8,
        sold: 62,
        material: 'Vang 14K',
        weight: 2.8,
        description: 'Nhẫn cưới vàng trắng 14K thiết kế đơn giản nhưng sang trọng, biểu tượng cho tình yêu vĩnh cửu.',
        shortDescription: 'Nhẫn cưới vàng trắng sang trọng',
        images: IMG.nhancuoivangtrang,
        isNew: true,
        rating: 4.9,
        totalReviews: 45,
    },
    {
        name: 'Nhẫn Solitaire Kim Cương',
        category: 'Nhan',
        price: 22500000,
        stock: 3,
        sold: 18,
        material: 'Platinum',
        weight: 4.2,
        gemstone: 'Kim cương 1ct',
        description: 'Nhẫn solitaire bạch kim đính kim cương 1 carat, kiểu dáng cổ điển vượt thời gian.',
        shortDescription: 'Nhẫn solitaire kim cương 1ct',
        images: IMG.nhansolitairekimcuong,
        isHot: true,
        rating: 5.0,
        totalReviews: 12,
    },
    {
        name: 'Nhẫn Vàng Hoa Văn Cổ Điển',
        category: 'Nhan',
        price: 5600000,
        originalPrice: 7200000,
        discount: 22,
        stock: 12,
        sold: 89,
        material: 'Vang 18K',
        weight: 3.1,
        description: 'Nhẫn vàng 18K chạm khắc hoa văn cổ điển, phù hợp đeo hàng ngày hoặc dự tiệc.',
        shortDescription: 'Nhẫn vàng hoa văn cổ điển',
        images: IMG.nhanvanghoavancodien,
        isSale: true,
        rating: 4.6,
        totalReviews: 31,
    },
    {
        name: 'Nhẫn Đôi Bạc',
        category: 'Nhan',
        price: 9800000,
        stock: 6,
        sold: 34,
        material: 'Bac',
        weight: 2.5,
        gemstone: 'Bac',
        description: 'Nhẫn bạc đôi siêu tinh tế cho các cặp đôi .',
        shortDescription: 'Nhẫn bạc đôi may mắn',
        images: IMG.nhandoibac,
        isNew: true,
        rating: 4.7,
        totalReviews: 19,
    },
    {
        name: 'Nhẫn Bạc Đá Sapphire Xanh',
        category: 'Nhan',
        price: 2200000,
        originalPrice: 2800000,
        discount: 21,
        stock: 20,
        sold: 156,
        material: 'Bac',
        weight: 2.0,
        gemstone: 'Sapphire xanh',
        description: 'Nhẫn bạc 925 đính đá sapphire xanh, thiết kế trẻ trung, giá cả phải chăng.',
        shortDescription: 'Nhẫn bạc sapphire xanh trẻ trung',
        images: IMG.nhanbacdaxanh,
        isHot: true,
        isSale: true,
        rating: 4.5,
        totalReviews: 67,
    },

    // ─── VÒNG TAY ───
    {
        name: 'Vòng Tay Swarovski Blue Gema Chính Hãng',
        category: 'Vong tay',
        price: 3500000,
        originalPrice: 4500000,
        discount: 22,
        stock: 12,
        sold: 78,
        material: 'Bac',
        weight: 8.5,
        gemstone: 'Ngọc trai tự nhiên',
        description: 'Vòng tay bạc kết hợp ngọc trai tự nhiên, mang đến vẻ đẹp thanh lịch và quý phái.',
        shortDescription: 'Vòng tay ngọc trai thanh lịch',
        images: IMG.bracelet,
        isHot: true,
        rating: 4.7,
        totalReviews: 34,
    },
    {
        name: 'Lắc Tay Swarovski Chính Hãng Angelic Bracelet',
        category: 'Vong tay',
        price: 12500000,
        originalPrice: 14800000,
        discount: 16,
        stock: 8,
        sold: 31,
        material: 'Bac',
        weight: 4.6,
        gemstone: 'Pha lê Swarovski round-cut',
        description: 'Lắc tay Swarovski 5733196 chính hãng thuộc dòng Una Angelic với thiết kế pha lê tròn lấp lánh, mạ Rhodium cao cấp, mang phong cách thanh lịch và sang trọng.',
        shortDescription: 'Lắc tay Una Angelic lấp lánh',
        images: IMG.braceletAngelic,
        isNew: true,
        isHot: true,
        rating: 5.0,
        totalReviews: 18,
    },
    {
        name: 'Vòng Tay Swarovski Chính Hãng Idyllia Bracelet',
        category: 'Vong tay',
        price: 11800000,
        originalPrice: 13900000,
        discount: 15,
        stock: 7,
        sold: 24,
        material: 'Bac',
        weight: 5.1,
        gemstone: 'Zirconia cao cấp',
        description: 'Là mẫu vòng tay Idyllia bangle với thiết kế trái tim độc đáo. Sản phẩm sử dụng zirconia cao cấp kết hợp crystal pavé và lớp mạ mixed metal, mang lại vẻ đẹp nổi bật và nữ tính.',
        shortDescription: 'Vòng tay Idyllia trái tim độc đáo',
        images: IMG.braceletIdyllia,
        isSale: true,
        rating: 4.9,
        totalReviews: 15,
    },
    {
        name: 'Vòng Tay Swarovski Chính Hãng Mesmera Bracelet',
        category: 'Vong tay',
        price: 14200000,
        originalPrice: 16500000,
        discount: 14,
        stock: 5,
        sold: 19,
        material: 'Bac',
        weight: 4.9,
        gemstone: 'Zirconia mixed cuts',
        description: 'Vòng tay Mesmera bracelet với thiết kế mixed cuts độc đáo. Sản phẩm sử dụng zirconia cao cấp cùng lớp mạ Rhodium, mang lại vẻ đẹp sang trọng và nổi bật.',
        shortDescription: 'Vòng tay Mesmera mixed cuts',
        images: IMG.braceletMesmera,
        isNew: true,
        rating: 4.8,
        totalReviews: 13,
    },
    {
        name: 'Vòng Tay Swarovski Chính Hãng Hyperbola Bangle',
        category: 'Vong tay',
        price: 13600000,
        originalPrice: 15800000,
        discount: 14,
        stock: 6,
        sold: 14,
        material: 'Bac',
        weight: 5.4,
        gemstone: 'Pha lê Swarovski pavé',
        description: 'Vòng tay Hyperbola bangle nổi bật với thiết kế trái tim hồng pavé tinh xảo. Sản phẩm sử dụng pha lê Swarovski kết hợp zirconia chuyển động và lớp mạ Rose Gold, mang lại vẻ đẹp sang trọng và cuốn hút.',
        shortDescription: 'Vòng tay Hyperbola trái tim pavé',
        images: IMG.braceletHyperbola,
        isHot: true,
        rating: 4.9,
        totalReviews: 11,
    },
    {
        name: 'Vòng Tay Swarovski Chính Hãng Constella Bracelet',
        category: 'Vong tay',
        price: 12900000,
        originalPrice: 14900000,
        discount: 13,
        stock: 9,
        sold: 17,
        material: 'Bac',
        weight: 4.7,
        gemstone: 'Crystal pearl & zirconia',
        description: 'Constella bracelet nổi bật với thiết kế crystal pearl và zirconia tinh tế. Sản phẩm sử dụng chất liệu cao cấp kết hợp lớp mạ Rhodium, mang lại vẻ đẹp thanh lịch và dễ phối đồ.',
        shortDescription: 'Vòng tay Constella thanh lịch',
        images: IMG.braceletConstella,
        isSale: true,
        rating: 4.8,
        totalReviews: 14,
    },

    // ─── DÂY CHUYỀN ───
    {
        name: 'Dây Chuyền Daniel Wellington Pavé',
        category: 'Day chuyen',
        price: 18500000,
        stock: 4,
        sold: 15,
        material: 'Vang 14K',
        weight: 8.5,
        gemstone: 'Pha lê',
        description: 'Dây chuyền Daniel Wellington Pavé đính đá lấp lánh, phong cách cao cấp.',
        shortDescription: 'Dây chuyền DW Pavé cao cấp',
        images: IMG.necklaceDw,
        isHot: true,
        rating: 4.8,
        totalReviews: 11,
    },
    {
        name: 'Dây Chuyền Swarovski Chính Hãng',
        category: 'Day chuyen',
        price: 5200000,
        originalPrice: 6500000,
        discount: 20,
        stock: 11,
        sold: 72,
        material: 'Bac',
        weight: 4.0,
        gemstone: 'Pha lê Swarovski',
        description: 'Dây chuyền Swarovski chính hãng, đá pha lê sáng rực, thiết kế tinh xảo.',
        shortDescription: 'Dây chuyền Swarovski chính hãng',
        images: IMG.necklaceSwarovski,
        isSale: true,
        rating: 4.7,
        totalReviews: 36,
    },

    {
        name: 'Dây Chuyền Kim Cương Solitaire',
        category: 'Day chuyen',
        price: 28000000,
        stock: 2,
        sold: 6,
        material: 'Platinum',
        weight: 3.8,
        gemstone: 'Kim cương 0.8ct',
        description: 'Dây chuyền bạch kim mặt kim cương solitaire 0.8ct, kiểu dáng thanh lịch cho phụ nữ hiện đại.',
        shortDescription: 'Dây chuyền kim cương solitaire',
        images: IMG.necklaceSwarovski,
        isNew: true,
        rating: 5.0,
        totalReviews: 4,
    },
    {
        name: 'Dây Chuyền Swarovski Chính Hãng Idyllia Pendant',
        category: 'Day chuyen',
        price: 5200000,
        originalPrice: 6500000,
        discount: 20,
        stock: 12,
        sold: 34,
        material: 'Bac',
        weight: 2.8,
        gemstone: 'Crystal trắng, Cubic zirconia',
        description: 'Idyllia pendant nổi bật với thiết kế mũi tên Cupid tinh xảo. Sản phẩm sử dụng crystal trắng, cubic zirconia và lớp mạ Rhodium, mang lại vẻ đẹp nữ tính, thanh lịch và hiện đại.',
        shortDescription: 'Idyllia pendant mũi tên Cupid tinh xảo',
        images: IMG.necklaceIdyllia,
        isNew: true,
        rating: 4.8,
        totalReviews: 21,
    },
    {
        name: 'Dây Chuyền Swarovski Chính Hãng Constella Pendant',
        category: 'Day chuyen',
        price: 4900000,
        originalPrice: 5900000,
        discount: 17,
        stock: 10,
        sold: 28,
        material: 'Bac',
        weight: 3.0,
        gemstone: 'Cubic zirconia',
        description: 'Constella pendant với thiết kế dancing stone màu hồng nổi bật. Sản phẩm sử dụng cubic zirconia cao cấp kết hợp lớp mạ rose gold-tone, mang lại vẻ đẹp thanh lịch và cuốn hút.',
        shortDescription: 'Constella pendant dancing stone màu hồng',
        images: IMG.necklaceConstella,
        isSale: true,
        rating: 4.7,
        totalReviews: 18,
    },
    {
        name: 'Dây Chuyền Swarovski Chính Hãng Matrix Pendant',
        category: 'Day chuyen',
        price: 5800000,
        originalPrice: 7000000,
        discount: 17,
        stock: 8,
        sold: 22,
        material: 'Bac',
        weight: 3.3,
        gemstone: 'Zirconia cao cấp',
        description: 'Matrix pendant với thiết kế mixed cuts độc đáo. Sản phẩm sử dụng zirconia cao cấp và lớp mạ Rhodium, mang lại vẻ đẹp sang trọng và thanh lịch.',
        shortDescription: 'Matrix pendant mixed cuts độc đáo',
        images: IMG.necklaceMatrix,
        rating: 4.8,
        totalReviews: 14,
    },
    {
        name: 'Dây Chuyền Swarovski Chính Hãng Hyperbola Pendant',
        category: 'Day chuyen',
        price: 6200000,
        originalPrice: 7600000,
        discount: 18,
        stock: 6,
        sold: 16,
        material: 'Bac',
        weight: 3.6,
        gemstone: 'Pha lê cao cấp',
        description: 'Hyperbola pendant nổi bật với thiết kế trái tim xanh tinh xảo, sử dụng pha lê cao cấp và lớp mạ Rhodium sáng bóng. Phụ kiện hoàn hảo cho phong cách thanh lịch và hiện đại.',
        shortDescription: 'Hyperbola pendant trái tim xanh tinh xảo',
        images: IMG.necklaceHyperbola,
        isHot: true,
        rating: 4.9,
        totalReviews: 12,
    },
    {
        name: 'Dây Chuyền Swarovski Chính Hãng Swan Pendant (Medium)',
        category: 'Day chuyen',
        price: 7100000,
        originalPrice: 8500000,
        discount: 16,
        stock: 7,
        sold: 13,
        material: 'Bac',
        weight: 3.9,
        gemstone: 'Pha lê trắng',
        description: 'Swan pendant Medium nổi bật với thiết kế thiên nga tinh xảo, sử dụng pha lê trắng cao cấp và lớp mạ Rhodium sáng bóng. Phụ kiện lý tưởng cho phong cách thanh lịch và hiện đại.',
        shortDescription: 'Swan pendant thiết kế thiên nga tinh xảo',
        images: IMG.necklaceSwanMedium,
        isNew: true,
        rating: 4.8,
        totalReviews: 11,
    },
    {
        name: 'Dây Chuyền Swarovski Chính Hãng Swan Pendant (Rose)',
        category: 'Day chuyen',
        price: 7300000,
        originalPrice: 8800000,
        discount: 17,
        stock: 5,
        sold: 9,
        material: 'Bac',
        weight: 4.0,
        gemstone: 'Pha lê',
        description: 'Swan pendant nổi bật với thiết kế thiên nga tinh xảo, kết hợp pha lê cao cấp và lớp mạ Rose Gold sang trọng. Phụ kiện hoàn hảo cho phong cách nữ tính và thanh lịch.',
        shortDescription: 'Swan pendant mạ Rose Gold sang trọng',
        images: IMG.necklaceSwanRose,
        isHot: true,
        rating: 4.9,
        totalReviews: 10,
    },

    // ─── BÔNG TAI ───
    {
        name: 'Bông Tai Swarovski Angelic Stud',
        category: 'Bong tai',
        price: 18900000,
        stock: 4,
        sold: 21,
        material: 'Bac',
        weight: 1.8,
        gemstone: 'Pha lê Swarovski',
        description: 'Bông tai Swarovski Angelic Stud chính hãng, thiết kế sang trọng, đẳng cấp.',
        shortDescription: 'Bông tai Swarovski Angelic',
        images: IMG.earringStud,
        isHot: true,
        rating: 5.0,
        totalReviews: 8,
    },
    {
        name: 'Bông Tai Swarovski Matrix Hoop Earrings',
        category: 'Bong tai',
        price: 5900000,
        stock: 10,
        sold: 40,
        material: 'Bac',
        weight: 2.2,
        gemstone: 'Crystal pearl, Round cut',
        description: 'Matrix hoop earrings, Crystal pearl, Round cut, White, Rhodium plated chính hãng, một thiết kế sang trọng của Swarovski.',
        shortDescription: 'Matrix hoop earrings pha lê & ngọc trai',
        images: IMG.earringMatrix,
        isNew: true,
        rating: 4.7,
        totalReviews: 12,
    },
    {
        name: 'Hoa Tai Swarovski Magic Stud (Snowflake)',
        category: 'Bong tai',
        price: 4500000,
        stock: 12,
        sold: 22,
        material: 'Bac',
        weight: 1.5,
        gemstone: 'Crystal, Blue',
        description: 'Magic stud earrings, Snowflake, Blue, Rhodium plated chính hãng, thiết kế tinh xảo và sang trọng.',
        shortDescription: 'Magic stud earrings bông tuyết',
        images: IMG.earringMagic,
        rating: 4.6,
        totalReviews: 9,
    },
    {
        name: 'Hoa Tai Swarovski Bella Drop Earrings',
        category: 'Bong tai',
        price: 6200000,
        stock: 8,
        sold: 15,
        material: 'Bac',
        weight: 2.6,
        gemstone: 'Heart, White',
        description: 'Bella drop earrings, Heart, White, Rhodium plated chính hãng, kiểu dáng nữ tính và sang trọng.',
        shortDescription: 'Bella drop earrings heart & crystal',
        images: IMG.earringBella,
        isHot: true,
        rating: 4.8,
        totalReviews: 11,
    },
    {
        name: 'Bông Tai Swarovski Dancing Swan Pierced Earrings',
        category: 'Bong tai',
        price: 7100000,
        stock: 6,
        sold: 9,
        material: 'Bac',
        weight: 2.9,
        gemstone: 'Pha lê cao cấp',
        description: 'Dancing Swan Pierced Earrings chính hãng, thiết kế thiên nga tinh xảo, sang trọng.',
        shortDescription: 'Dancing Swan pierced earrings',
        images: IMG.earringSwanDancing,
        rating: 4.9,
        totalReviews: 7,
    },
    {
        name: 'Bông Tai Swarovski Solitaire Stud Earrings',
        category: 'Bong tai',
        price: 4800000,
        stock: 14,
        sold: 27,
        material: 'Bac',
        weight: 1.4,
        gemstone: 'Round cut, Blue',
        description: 'Solitaire stud earrings, Round cut, Blue, Rhodium plated chính hãng, phong cách cổ điển thanh lịch.',
        shortDescription: 'Solitaire stud earrings',
        images: IMG.earringSolitaire,
        isSale: true,
        rating: 4.7,
        totalReviews: 13,
    },
    {
        name: 'Bông Tai Swarovski Una Angelic Stud',
        category: 'Bong tai',
        price: 1890000,
        stock: 10,
        sold: 20,
        material: 'Bac',
        weight: 1.6,
        gemstone: 'Round cut & crystal pavé',
        description: 'Una Angelic Stud earrings chính hãng, viên đá round cut trung tâm kèm crystal pavé tinh xảo.',
        shortDescription: 'Una Angelic Stud',
        images: IMG.earringUnaAngelic,
        rating: 4.8,
        totalReviews: 10,
    },
    {
        name: 'Khuyên Tai Swarovski Heart Chroma',
        category: 'Bong tai',
        price: 4500000,
        stock: 10,
        sold: 58,
        material: 'Bac',
        weight: 1.5,
        gemstone: 'Pha lê Swarovski',
        description: 'Khuyên tai Swarovski Heart Chroma chính hãng, phong cách thanh lịch hiện đại.',
        shortDescription: 'Khuyên tai Swarovski Heart',
        images: IMG.earringHeart,
        isNew: true,
        rating: 4.8,
        totalReviews: 25,
    },
    {
        name: 'Bông Tai Swarovski Chính Hãng Premium',
        category: 'Bong tai',
        price: 12500000,
        stock: 5,
        sold: 19,
        material: 'Bac',
        weight: 3.2,
        gemstone: 'Pha lê Swarovski',
        description: 'Bông tai Swarovski Premium đính pha lê, ánh sáng lấp lánh đẳng cấp.',
        shortDescription: 'Bông tai Swarovski Premium',
        images: IMG.earringStud,
        isHot: true,
        rating: 4.9,
        totalReviews: 14,
    },

    // ─── MẶT DÂY ───
    
    {
        name: 'Mặt Dây Bạc Thần Tài',
        category: 'Mat day',
        price: 1200000,
        stock: 0,
        sold: 245,
        material: 'Bac',
        weight: 4.0,
        description: 'Mặt dây bạc Thần Tài, biểu tượng thu hút tài lộc trong văn hóa Việt Nam.',
        shortDescription: 'Mặt dây bạc Thần Tài tài lộc',
        images: [IMG.pendant[0], IMG.pendant[1]],
        isHot: true,
        rating: 4.2,
        totalReviews: 102,
    },

    // ─── TRANG SỨC CƯỚI ───
    {
        name: 'Bộ Trang Sức Cưới Kim Cương',
        category: 'Trang suc cuoi',
        price: 45000000,
        stock: 2,
        sold: 5,
        material: 'Platinum',
        weight: 15.0,
        gemstone: 'Kim cương 2ct tổng',
        description: 'Bộ trang sức cưới gồm nhẫn, dây chuyền và bông tai kim cương, thiết kế đồng bộ sang trọng.',
        shortDescription: 'Bộ trang sức cưới kim cương cao cấp',
        images: [IMG.wedding[4],IMG.wedding[5], IMG.wedding[6]],
        isNew: true,
        isHot: true,
        rating: 5.0,
        totalReviews: 3,
    },
    {
        name: 'Nhẫn Cưới Đôi Vàng 18K',
        category: 'Trang suc cuoi',
        price: 12000000,
        originalPrice: 15000000,
        discount: 20,
        stock: 6,
        sold: 34,
        material: 'Vang 18K',
        weight: 5.6,
        description: 'Cặp nhẫn cưới vàng 18K thiết kế đôi, khắc tên theo yêu cầu, biểu tượng tình yêu vĩnh cửu.',
        shortDescription: 'Cặp nhẫn cưới vàng 18K đôi',
        images: [IMG.wedding[9], IMG.wedding[10]],
        isSale: true,
        rating: 4.9,
        totalReviews: 22,
    },
    
    {
        name: 'Bông Tai Cô Dâu Kim Cương',
        category: 'Trang suc cuoi',
        price: 22000000,
        stock: 3,
        sold: 9,
        material: 'Platinum',
        weight: 2.5,
        gemstone: 'Kim cương 0.5ct',
        description: 'Bông tai cô dâu bạch kim đính kim cương, thiết kế chandelier lấp lánh.',
        shortDescription: 'Bông tai cô dâu kim cương lấp lánh',
        images: [IMG.wedding[7], IMG.wedding[8]],
        isHot: true,
        rating: 5.0,
        totalReviews: 6,
    },
    {
        name: 'Vòng Tay Cưới Vàng Trắng',
        category: 'Trang suc cuoi',
        price: 6800000,
        originalPrice: 8500000,
        discount: 20,
        stock: 10,
        sold: 41,
        material: 'Vang 14K',
        weight: 4.8,
        description: 'Vòng tay cưới vàng trắng 14K, thiết kế mảnh mai phù hợp đeo cùng váy cưới.',
        shortDescription: 'Vòng tay cưới vàng trắng mảnh mai',
        images: [IMG.wedding[3], IMG.wedding[4]],
        isSale: true,
        rating: 4.7,
        totalReviews: 19,
    },
    {
        name: 'Bộ Nhẫn Cưới Bạc Đôi',
        category: 'Trang suc cuoi',
        price: 3500000,
        stock: 20,
        sold: 167,
        material: 'Bac',
        weight: 4.0,
        description: 'Bộ nhẫn cưới bạc 925 đôi, giá cả phải chăng, thiết kế đơn giản thanh lịch.',
        shortDescription: 'Bộ nhẫn cưới bạc giá tốt',
        images: IMG.wedding,
        isHot: true,
        rating: 4.4,
        totalReviews: 78,
    },
];

const products = rawProducts.map((p) => ({
    ...p,
    slug: generateSlug(p.name),
}));

const seedDatabase = async () => {
    try {
        await mongoose.connect(process.env.MONGO_DB_URL);
        await Product.deleteMany({});
        await Product.insertMany(products);
        const counts = await Product.aggregate([
            { $group: { _id: '$category', count: { $sum: 1 } } },
        ]);
        console.log('Seed data thành công! Tổng:', products.length, 'sản phẩm');
        counts.forEach((c) => console.log(`  - ${c._id}: ${c.count} sản phẩm`));
        process.exit(0);
    } catch (error) {
        console.error('Lỗi seed:', error);
        process.exit(1);
    }
};

seedDatabase();
